# Site settings
title: Jake Hendy
email: me+web@jakehendy.com
description: "Jake Hendy. That guy, that dev. By day,IT Practitioner at the Met Office. By night... gamer, gymer and ninjer... er ninja."
baseurl: ""
url: "http://www.jakehendy.com"

# Build settings
markdown: kramdown
permalink: pretty
