# Dependencies
markdown:         redcarpet
highlighter:      pygments

gems:
  - jemoji

# Permalinks
permalink:        pretty

# Setup
title:            'Jake Hendy'
tagline:          'Gamer, Programmer, Gym Lover. All rolled in to one package'
description:      'Jake Hendy... by day an IT Practitioner at The Met Office. By night, a gamer, gym lover and ninjer... erm, ninja.'
url:              http://jakehendy.com
baseurl:          '/'
paginate:         5
version:          1.0.0


author:
  name:           'Jake Hendy'
  url:            https://twitter.com/JakeHendy
